### ISSUE TITLE
Don't require the `emacs` feature

### ISSUE THREAD

**Issue by tarsius** [natelastname/tpl-dumper#1]
You do not need to require the feature (aka library) `emacs`. In fact there does not appear to be a library that provides that feature. For some reason `(require 'emacs)` does not signal an error, even though requiring a non-existent library would normally do that. I am guessing handling of this "feature" is a special case left over from when XEmacs was still a thing.

**Comment by natelastname** [comment]
Interesting, I probably just copied that from somewhere. Should be fixed now

**Comment by tarsius** [comment]
Thanks!

> I probably just copied that from somewhere.

Maybe, but not from one of the 8000 packages tracked on the Emacsmirror. Among those, your package was the only one that did this. :grin:
